title: Beau Gunderson
email: beau@beaugunderson.com
description: Beau Gunderson
baseurl: /blog
url: https://beaugunderson.com
twitter_username: beaugunderson
github_username: beaugunderson

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
